DATA:
    ROOT: '/PATH/TO/videos/folder'
    TRAIN_FILE: '/root/autodl-tmp/Kinetics-400/kinetics400_train_list_videos.txt'
    VAL_FILE: '/root/autodl-tmp/Kinetics-400/kinetics400_val_list_videos.txt'
    DATASET: kinetics400
    NUM_FRAMES: 32
    NUM_CLASSES: 400
    LABEL_LIST: 'labels/kinetics_400_labels.csv'
    DES_SPATIAL: 'descriptors/k400/spatio_descriptors/4_descriptors.json'
    DES_TEMPORAL: 'descriptors/k400/temporal_descriptors/4_descriptors.json'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 4 # Effective BS 256
    ACCUMULATION_STEPS: 8
    LR: 8e-06
    EPOCHS: 10
TRAINER:
  OST:
    ZS_EVAL: False # Make True only during test mode to evaluate zero-shot vanilla CLIP performance
    USE: "both" # both refers to complete fine-tuning of CLIP (text+image encoders)
    N: 4
AUG:
    LABEL_SMOOTH: 0.
    COLOR_JITTER: 0.8
    GRAY_SCALE: 0.2
    MIXUP: 0.
    CUTMIX: 0.
    MIXUP_SWITCH_PROB: 0.